/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TetrisFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHECKIN_COOLDOWN"
      | "CHECKIN_REWARD"
      | "FIRST_CONNECT_REWARD"
      | "canCheckIn"
      | "checkIn"
      | "claimFirstConnectBonus"
      | "getEncryptedScore"
      | "getPlays"
      | "getScoreInfo"
      | "getTotalScores"
      | "lastCheckin"
      | "nextScoreId"
      | "owner"
      | "plays"
      | "protocolId"
      | "scores"
      | "setSubmissionFee"
      | "submissionFee"
      | "submitScore"
      | "totalScores"
      | "usePlay"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckInCompleted"
      | "FeesWithdrawn"
      | "ScoreSubmitted"
      | "SubmissionFeeChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHECKIN_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHECKIN_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FIRST_CONNECT_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canCheckIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "checkIn", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimFirstConnectBonus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlays",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalScores",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCheckin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextScoreId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "plays", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubmissionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalScores",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usePlay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CHECKIN_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHECKIN_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FIRST_CONNECT_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canCheckIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimFirstConnectBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlays", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getScoreInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCheckin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextScoreId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plays", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scores", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSubmissionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usePlay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CheckInCompletedEvent {
  export type InputTuple = [player: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [player: string, timestamp: bigint];
  export interface OutputObject {
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    scoreId: BigNumberish,
    player: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    scoreId: bigint,
    player: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    scoreId: bigint;
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionFeeChangedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TetrisFHE extends BaseContract {
  connect(runner?: ContractRunner | null): TetrisFHE;
  waitForDeployment(): Promise<this>;

  interface: TetrisFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHECKIN_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  CHECKIN_REWARD: TypedContractMethod<[], [bigint], "view">;

  FIRST_CONNECT_REWARD: TypedContractMethod<[], [bigint], "view">;

  canCheckIn: TypedContractMethod<
    [player: AddressLike],
    [[boolean, bigint] & { canCheckin: boolean; lastCheckinTime: bigint }],
    "view"
  >;

  checkIn: TypedContractMethod<[], [boolean], "nonpayable">;

  claimFirstConnectBonus: TypedContractMethod<
    [signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedScore: TypedContractMethod<
    [scoreId: BigNumberish],
    [
      [string, string, string] & { score: string; lines: string; level: string }
    ],
    "view"
  >;

  getPlays: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  getScoreInfo: TypedContractMethod<
    [scoreId: BigNumberish],
    [
      [string, bigint, boolean] & {
        player: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getTotalScores: TypedContractMethod<[], [bigint], "view">;

  lastCheckin: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  nextScoreId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  plays: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  scores: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        player: string;
        encryptedScore: string;
        encryptedLines: string;
        encryptedLevel: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  setSubmissionFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  submissionFee: TypedContractMethod<[], [bigint], "view">;

  submitScore: TypedContractMethod<
    [
      encryptedScore: BytesLike,
      encryptedLines: BytesLike,
      encryptedLevel: BytesLike,
      scoreProof: BytesLike,
      linesProof: BytesLike,
      levelProof: BytesLike
    ],
    [void],
    "payable"
  >;

  totalScores: TypedContractMethod<[], [bigint], "view">;

  usePlay: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHECKIN_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CHECKIN_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FIRST_CONNECT_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canCheckIn"
  ): TypedContractMethod<
    [player: AddressLike],
    [[boolean, bigint] & { canCheckin: boolean; lastCheckinTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "claimFirstConnectBonus"
  ): TypedContractMethod<[signature: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedScore"
  ): TypedContractMethod<
    [scoreId: BigNumberish],
    [
      [string, string, string] & { score: string; lines: string; level: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlays"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScoreInfo"
  ): TypedContractMethod<
    [scoreId: BigNumberish],
    [
      [string, bigint, boolean] & {
        player: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalScores"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastCheckin"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextScoreId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "plays"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scores"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        player: string;
        encryptedScore: string;
        encryptedLines: string;
        encryptedLevel: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setSubmissionFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submissionFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [
      encryptedScore: BytesLike,
      encryptedLines: BytesLike,
      encryptedLevel: BytesLike,
      scoreProof: BytesLike,
      linesProof: BytesLike,
      levelProof: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalScores"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usePlay"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CheckInCompleted"
  ): TypedContractEvent<
    CheckInCompletedEvent.InputTuple,
    CheckInCompletedEvent.OutputTuple,
    CheckInCompletedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionFeeChanged"
  ): TypedContractEvent<
    SubmissionFeeChangedEvent.InputTuple,
    SubmissionFeeChangedEvent.OutputTuple,
    SubmissionFeeChangedEvent.OutputObject
  >;

  filters: {
    "CheckInCompleted(address,uint256)": TypedContractEvent<
      CheckInCompletedEvent.InputTuple,
      CheckInCompletedEvent.OutputTuple,
      CheckInCompletedEvent.OutputObject
    >;
    CheckInCompleted: TypedContractEvent<
      CheckInCompletedEvent.InputTuple,
      CheckInCompletedEvent.OutputTuple,
      CheckInCompletedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "ScoreSubmitted(uint256,address,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "SubmissionFeeChanged(uint256)": TypedContractEvent<
      SubmissionFeeChangedEvent.InputTuple,
      SubmissionFeeChangedEvent.OutputTuple,
      SubmissionFeeChangedEvent.OutputObject
    >;
    SubmissionFeeChanged: TypedContractEvent<
      SubmissionFeeChangedEvent.InputTuple,
      SubmissionFeeChangedEvent.OutputTuple,
      SubmissionFeeChangedEvent.OutputObject
    >;
  };
}
